//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificateExist
    {
        public string Id { get; set; }
        public int statusCertificate { get; set; }
        public string dayCareCenterId { get; set; }
        public byte[] picture { get; set; }
        public System.DateTime issueDate { get; set; }
        public int certificateId { get; set; }
    
        public virtual statusCertificate statusCertificate1 { get; set; }
        public virtual dayCareCenter dayCareCenter { get; set; }
        public virtual possibleCertificate possibleCertificate { get; set; }
    }
}
