//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayCareCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dayCareCenter()
        {
            this.problemsExist = new HashSet<problemsExist>();
            this.certificateExist = new HashSet<certificateExist>();
        }
    
        public string Id { get; set; }
        public string dayCareCenterDirectorName { get; set; }
        public string directorId { get; set; }
        public string maintenanceManId { get; set; }
        public string welfareSymbol { get; set; }
        public string economySymbol { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<problemsExist> problemsExist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificateExist> certificateExist { get; set; }
    }
}
