//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dayCareCenter> dayCareCenter { get; set; }
        public virtual DbSet<permissions> permissions { get; set; }
        public virtual DbSet<possibleProblems> possibleProblems { get; set; }
        public virtual DbSet<statusProblem> statusProblem { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<problemsExist> problemsExist { get; set; }
        public virtual DbSet<possibleCertificate> possibleCertificate { get; set; }
        public virtual DbSet<statusCertificate> statusCertificate { get; set; }
        public virtual DbSet<certificateExist> certificateExist { get; set; }
    }
}
